quadrantChart
    title Reach and engagement of campaigns
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    3Commas: [0.6, 0.7]
    Cryptohopper: [0.5, 0.6]
    TradeSanta: [0.4, 0.5]
    Pionex: [0.3, 0.4]
    Bitsgap: [0.7, 0.8]
    Our Target Product: [0.5, 0.6]